FROM ghcr.io/nyamisty/hexvault-docker

RUN apt-get update && apt-get install -y openssl

ENV VAULT_HOSTNAME=vault

ADD fake_hexrays_ca /opt/fake_hexrays_ca
ADD start2.sh /
ADD teamssrv-anon.hexlic /opt/hexvault

CMD bash /start2.sh